//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Samples.NLayerApp.Domain.MainBoundedContext.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Samples.NLayerApp.Domain.MainBoundedContext.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot deposit money in locked account.
        /// </summary>
        internal static string exception_BankAccountCannotDeposit {
            get {
                return ResourceManager.GetString("exception_BankAccountCannotDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot withdraw in bankaccount, this is locked or amount is greather than balance.
        /// </summary>
        internal static string exception_BankAccountCannotWithdraw {
            get {
                return ResourceManager.GetString("exception_BankAccountCannotWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid amount for withdraw operation.
        /// </summary>
        internal static string exception_BankAccountInvalidWithdrawAmount {
            get {
                return ResourceManager.GetString("exception_BankAccountInvalidWithdrawAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country is null or Country is in Transient state.
        /// </summary>
        internal static string exception_CannotAssociateTransientOrNullCountry {
            get {
                return ResourceManager.GetString("exception_CannotAssociateTransientOrNullCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is null or Customer is in Transient state.
        /// </summary>
        internal static string exception_CannotAssociateTransientOrNullCustomer {
            get {
                return ResourceManager.GetString("exception_CannotAssociateTransientOrNullCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product is null or Product is in Transient state.
        /// </summary>
        internal static string exception_CannotAssociateTransientOrNullProduct {
            get {
                return ResourceManager.GetString("exception_CannotAssociateTransientOrNullProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot transfer money to the same bank account.
        /// </summary>
        internal static string exception_CannotTransferMoneyWhenFromIsTheSameAsTo {
            get {
                return ResourceManager.GetString("exception_CannotTransferMoneyWhenFromIsTheSameAsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data in order line, check the values, amount of items must be greater than zero.
        /// </summary>
        internal static string exception_InvalidDataForOrderLine {
            get {
                return ResourceManager.GetString("exception_InvalidDataForOrderLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid order number pattern .
        /// </summary>
        internal static string exception_OrderNumberSpecificationInvalidOrderNumberPattern {
            get {
                return ResourceManager.GetString("exception_OrderNumberSpecificationInvalidOrderNumberPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit from account with identifier {0}.
        /// </summary>
        internal static string messages_TransactionFromMessage {
            get {
                return ResourceManager.GetString("messages_TransactionFromMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw to account with identifier {0}.
        /// </summary>
        internal static string messages_TransactionToMessage {
            get {
                return ResourceManager.GetString("messages_TransactionToMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bank account number cannot be null or empty string.
        /// </summary>
        internal static string validation_BankAccountBankAccountNumberCannotBeNull {
            get {
                return ResourceManager.GetString("validation_BankAccountBankAccountNumberCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bank account check digits cannot be null or empty string.
        /// </summary>
        internal static string validation_BankAccountBankCheckDigitsCannotBeNull {
            get {
                return ResourceManager.GetString("validation_BankAccountBankCheckDigitsCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bank account national bank code cannot be null or empty string.
        /// </summary>
        internal static string validation_BankAccountBankNationalBankCodeCannotBeNull {
            get {
                return ResourceManager.GetString("validation_BankAccountBankNationalBankCodeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bank account office number cannot be null or empty string.
        /// </summary>
        internal static string validation_BankAccountBankOfficeNumberCannotBeNull {
            get {
                return ResourceManager.GetString("validation_BankAccountBankOfficeNumberCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer id  in bank account cannot be empty.
        /// </summary>
        internal static string validation_BankAccountCustomerIdIsEmpty {
            get {
                return ResourceManager.GetString("validation_BankAccountCustomerIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bank account number cannot be null.
        /// </summary>
        internal static string validation_BankAccountNumberCannotBeNull {
            get {
                return ResourceManager.GetString("validation_BankAccountNumberCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountryISOCode cannot be null or empty string.
        /// </summary>
        internal static string validation_CountryCountryISOCodeCannotBeNull {
            get {
                return ResourceManager.GetString("validation_CountryCountryISOCodeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountryName cannot be null or empty string.
        /// </summary>
        internal static string validation_CountryCountryNameCannotBeNull {
            get {
                return ResourceManager.GetString("validation_CountryCountryNameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountryId is not associated for this Customer.
        /// </summary>
        internal static string validation_CustomerCountryIdCannotBeEmpty {
            get {
                return ResourceManager.GetString("validation_CustomerCountryIdCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FirstName property cannot be null or empty string.
        /// </summary>
        internal static string validation_CustomerFirstNameCannotBeNull {
            get {
                return ResourceManager.GetString("validation_CustomerFirstNameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LastName property cannot be null or empty string.
        /// </summary>
        internal static string validation_CustomerLastNameCannotBeBull {
            get {
                return ResourceManager.GetString("validation_CustomerLastNameCannotBeBull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is null or Customer is in Transient state.
        /// </summary>
        internal static string validation_OrderCustomerIdCannotBenull {
            get {
                return ResourceManager.GetString("validation_OrderCustomerIdCannotBenull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Amount property cannot be less than 1.
        /// </summary>
        internal static string validation_OrderLineAmountLessThanOne {
            get {
                return ResourceManager.GetString("validation_OrderLineAmountLessThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Discount cannot be less than 0 or greater than 1.
        /// </summary>
        internal static string validation_OrderLineDiscountCannotBeLessThanZeroOrGreaterThanOne {
            get {
                return ResourceManager.GetString("validation_OrderLineDiscountCannotBeLessThanZeroOrGreaterThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderLine cannot have associated order.
        /// </summary>
        internal static string validation_OrderLineOrderIdIsEmpty {
            get {
                return ResourceManager.GetString("validation_OrderLineOrderIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product id cannot be a empty identifier.
        /// </summary>
        internal static string validation_OrderLineProductIdCannotBeNull {
            get {
                return ResourceManager.GetString("validation_OrderLineProductIdCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitPrice cannot be less than zero.
        /// </summary>
        internal static string validation_OrderLineUnitPriceLessThanZero {
            get {
                return ResourceManager.GetString("validation_OrderLineUnitPriceLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount in stock cannot be less than zero.
        /// </summary>
        internal static string validation_ProductAmountLessThanZero {
            get {
                return ResourceManager.GetString("validation_ProductAmountLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description cannot be null or empty.
        /// </summary>
        internal static string validation_ProductDescriptionCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("validation_ProductDescriptionCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title cannot be null or empty.
        /// </summary>
        internal static string validation_ProductTitleCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("validation_ProductTitleCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitPrice in stock cannot be less than zero.
        /// </summary>
        internal static string validation_ProductUnitPriceLessThanZero {
            get {
                return ResourceManager.GetString("validation_ProductUnitPriceLessThanZero", resourceCulture);
            }
        }
    }
}
